# Creating matrix with Numpy

In [6]:
import numpy as np

### creating matrix from pre defined multidimensional list
```python
listed_matrix = [[1,2,3],[4,5,6],[7,8,9]]
```

In [7]:
listed_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np_array = np.array(listed_matrix)

### Display created matrix

In [9]:
type(np_array)

numpy.ndarray

## Creating matrix filled with zero, ones or else

In [10]:
zero_matrix = np.zeros((3,5))
print(zero_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
ones_matrix = np.ones((4,3), dtype=np.float64)
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Empty matrix

In [14]:
empty_matrix = np.empty((4,4), dtype=np.float32)
print(empty_matrix)

[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 2.006659e-42 0.000000e+00]
 [0.000000e+00 9.918370e-39 0.000000e+00 1.001021e-38]]


## Diagonal Matrix

In [15]:
diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [16]:
from PIL import Image

In [17]:
image = Image.open('img.JPG')

FileNotFoundError: [Errno 2] No such file or directory: 'img.JPG'